server:
  port: 8800

spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: 用户服务
          uri: lb://user-service
          predicates:
            - Path=/user-service/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/