server:
  port: 8200
  servlet:
    context-path: /order-service

spring:
  application:
    name: product-service
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/