server:
  port: 8101
  servlet:
    context-path: /product-service

spring:
  application:
    name: product-service
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    metadata-map:
      routingTag: xzh